pipeline {
  agent any

  stages {
    stage('Build') {
      steps{
        echo 'Building application'
      }
    }
    stage('Test'){
      when{
        anyOf{
          branch 'main'
          branch 'dev'
        }
      }
      steps{
        echo 'running tests'
      }
    }
    stage('Deploy') {
      when{
        branch 'main'
      }
      steps{
        sh './deploy.sh'
      }
    }
  }
}
    
